import os
import django
from django.conf import settings
from django.db import models, connection
from django.core.management import call_command
from django.db.migrations.executor import MigrationExecutor
from django.db.migrations.state import ProjectState

# Configure Django settings
settings.configure(
    DATABASES={
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    },
    INSTALLED_APPS=[
        'django.contrib.contenttypes',
        'django.contrib.auth',
        'test_app',
    ],
    MIGRATION_MODULES={
        'test_app': 'test_app.migrations'
    }
)

# Initialize Django
django.setup()

# Define a test model
class TestModel(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        app_label = 'test_app'

# Create initial migration
call_command('makemigrations', 'test_app')

# Apply initial migration
call_command('migrate', 'test_app')

# Alter the model to add choices
class TestModel(models.Model):
    name = models.CharField(max_length=100, choices=[('A', 'Option A'), ('B', 'Option B')])

    class Meta:
        app_label = 'test_app'

# Create migration for altering the field
call_command('makemigrations', 'test_app')

# Capture the SQL generated by the migration
executor = MigrationExecutor(connection)
executor.loader.build_graph()  # reload.
targets = executor.loader.graph.leaf_nodes()
plan = executor.migration_plan(targets)

for migration, backwards in plan:
    if not backwards:
        state = executor.loader.project_state((migration.app_label, migration.name), at_end=False)
        schema_editor = executor.connection.schema_editor(collect_sql=True)
        with schema_editor:
            migration.apply(state, schema_editor)
        for statement in schema_editor.collected_sql:
            print(statement)

print("Script completed successfully, no errors.")
