# Generated by Django 4.1.dev20220406104243 on 2024-07-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="name",
            field=models.CharField(
                choices=[("A", "Option A"), ("B", "Option B")], max_length=100
            ),
        ),
    ]
