# Generated by Django 4.1.dev20220406104243 on 2024-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0008_alter_testmodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
