# Generated by Django 4.2.dev20221122132623 on 2024-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityBlackListed",
            fields=[
                (
                    "blacklistid",
                    models.IntegerField(
                        db_column="BlacklistID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "sectorid",
                    models.IntegerField(blank=True, db_column="SectorID", null=True),
                ),
            ],
            options={
                "db_table": "Activity_BlackListed",
            },
        ),
    ]
