# Generated by Django 3.0.dev20190430084830 on 2024-07-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.IntegerField(blank=True, null=True)),
                ('flag', models.BooleanField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='testconstraint',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('field_1__isnull', False), ('flag__exact', True)), ('flag__exact', False), _connector='OR'), name='field_1_has_value_if_flag_set'),
        ),
    ]
