# Generated by Django 3.1 on 2024-06-28 06:21

from django.db import migrations, models
import test_app.models.Outer


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', test_app.models.Outer.Inner(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
