# Generated by Django 4.0.dev20210407150753 on 2024-06-28 17:21

from django.db import migrations
import reproduce_bug.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', reproduce_bug.models.MyAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
