# Generated by Django 4.1.dev20220131103324 on 2024-07-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0002_mymodel2'),
    ]

    operations = [
    ]
