# Generated by Django 5.0.dev20230320050210 on 2024-07-30 09:20

import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0002_test_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testmodel",
            name="created_at",
        ),
    ]
