# Generated by Django 3.1 on 2024-07-29 18:06

from django.db import migrations, models
import test1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', test1.models.Outer.Inner(max_length=20)),
            ],
        ),
    ]
