# Generated by Django 3.1 on 2024-07-29 18:06

from django.db import migrations, models
import enumfields.fields
import test1.models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', enumfields.fields.EnumField(enum=test1.models.Thing.State, max_length=10)),
            ],
        ),
    ]
